; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Screencast Capture Lite"
#define MyAppVersion "1.1"
#define MyAppPublisher "Accord.NET Framework"
#define MyAppURL "http://accord.googlecode.com"
#define MyAppExeName "ScreenCapture.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A4DAE6AA-2ACE-4905-9124-635C0F700054}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
LicenseFile=..\..\License.txt
OutputBaseFilename=ScreencastCaptureLiteSetup
Compression=lzma
SolidCompression=yes
OutputDir=..\bin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Components]
Name: "bin"; Description: "Program executable"; Types: full compact custom; Flags: fixed
Name: "src"; Description: "Source code files"; Types: full custom;

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\Binaries\*";        DestDir: "{app}\Binaries";  Components: bin; 
Source: "..\..\Sources\*";         DestDir: "{app}\Sources";   Components: src; Flags: recursesubdirs; Excludes: "*.~*,\TestResults,\bin,\obj,*.sdf,*.suo,*.user,*.vsp,*.shfbproj_*,*.pidb"
Source: "..\..\Copyright.txt";     DestDir: "{app}";           Components: bin
Source: "..\..\License.txt";       DestDir: "{app}";           Components: bin
Source: "..\..\Release notes.txt"; DestDir: "{app}";           Components: bin

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\Binaries\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

